const { createClient } = require('@supabase/supabase-js')

const supabase = createClient(
  'https://oujxxenmljyytkkgmagf.supabase.co',
  'sb_publishable_IbvkFQ-yyDkxEqjwzH27lQ_zwwu2SGP',
  
)

const metalcollection = [

  {
    band: 'Iron Maiden',
    title: 'Powerslave',
    image: '/src/images/ironmaiden-1.jpg',
    date: 'July 23rd, 1984',
    length: '(51:12)',
    genre: 'Heavy Metal',
  },
  {
    band: 'Orbit Culture',
    title: 'Death above life',
    image: '/src/images/orbitculture-1.jpg',
    date: 'October 03rd, 2025',
    length: '(48:34)',
    genre: 'Death Metal',
  },
  {
    band: 'Orbit Culture',
    title: 'Descent',
    image: '/src/images/orbitculture-2.jpg',
    date: 'August 18th, 2023',
    length: '(51:12)',
    genre: 'Death Metal',
  },
  {
    band: 'Whitechapel',
    title: 'Hymmns in Dissonance',
    image: '/src/images/whitechapel-1.jpg',
    date: 'March 07th, 2025',
    length: '(43:17)',
    genre: 'Hardcore,Grindcore',
  },
  {
    band: 'Black Sabbath',
    title: 'Heaven and Hell',
    image: '/src/images/blacksabbath-1.jpg',
    date: 'April 25th, 1980',
    length: '(39:48)',
    genre: 'Heavy Metal, Doom Metal',
  },
  {
    band: 'Neckbreakker',
    title: 'Within The viscera',
    image: '/src/images/neckbreakker-1.jpg',
    date: 'December 06th, 2024',
    length: '(46:09)',
    genre: 'Death Metal',
  },
  {
    band: 'Lorna Shore',
    title: 'I feel the everblack festering within me',
    image: '/src/images/lornashore-1.jpg',
    date: 'September 29th, 2025',
    length: '(66:31)',
    genre: 'Deathcore',
  },
  {
    band: 'Mötorhead',
    title: 'Overnight session',
    image: '/src/images/motorhead-1.jpg',
    date: 'October 15th 1996',
    length: '(41:19)',
    genre: 'Heavy Rock',
  },
  {
    band: 'Sacred Reich',
    title: 'awakening',
    image: '/src/images/sacredreich-1.jpg',
    date: 'August 23rd, 2019',
    length: '(31:28)',
    genre: 'Trash Metal',
  },
  {
    band: 'Iron Maiden',
    title: 'Made in England',
    image: '/src/images/ironmaiden-2.jpg',
    date: 'March 25th, 2013',
    length: '(100:22)',
    genre: 'Heavy Metal',
  },
  {
    band: 'Neaera',
    title: 'All is dust',
    image: '/src/images/neaera-1.jpg',
    date: 'June 28th, 2024',
    length: '(47:40)',
    genre: 'Death Metal',
  },
  {
    band: 'Mötorhead',
    title: 'The Löst Tapes, Vol. 2 (Live in Norwich, 1998)',
    image: '/src/images/motorhead-2.jpg',
    date: 'December 24th, 2021',
    length: '(47:40)',
    genre: 'Death Metal',
  },
  {
    band: 'Type of Negative',
    title: 'Life is killing me',
    image: '/src/images/typeofnegative-1.jpg',
    date: 'April 19th, 2024',
    length: '(74:33)',
    genre: 'Goth Metal',
  },
  {
    band: 'Tool',
    title: 'Undertow',
    image: '/src/images/tool-1.jpg',
    date: 'January 01st, 1993',
    length: '(68:13)',
    genre: 'Underground Metal',
  },
  {
    band: 'Iron Maiden',
    title: 'The Number of the Beast',
    image: '/src/images/ironmaiden-3.jpg',
    date: 'March 22nd, 1982',
    length: '(40:22)',
    genre: 'Heavy Metal',
  },
  {
    band: 'The Black Dahlia Murder',
    title: 'Servitude',
    image: '/src/images/theblackdahlia-1.jpg',
    date: 'September 27th, 2024',
    length: '(32:49)',
    genre: 'Death Metal',
  },
  {
    band: 'Killswitch Engage',
    title: 'Atonement',
    image: '/src/images/killswitch-1.jpg',
    date: 'August 16th, 2019',
    length: '(39:02)',
    genre: 'Death Metal',
  },
  {
    band: 'Opeth',
    title: 'Ghost reveries',
    image: '/src/images/opeth-1.jpg',
    date: 'August 30th, 2005',
    length: '(66:46)',
    genre: 'Doom Death Metal, Progressive Metal',
  },
  {
    band: 'Borknagar',
    title: 'Fall',
    image: '/src/images/borknagar-1.jpg',
    date: 'February 23rd, 2024',
    length: '(54:30)',
    genre: 'Progressive Metal',
  },
  {
    band: 'Iron Maiden',
    title: 'Life after death',
    image: '/src/images/ironmaiden-4.jpg',
    date: 'August 01st, 1985',
    length: '(102:54)',
    genre: 'Heavy Metal',
  },
  {
    band: 'System of a Down',
    title: 'Toxicity',
    image: '/src/images/systemofadown-1.jpg',
    date: 'September 04th, 2001',
    length: '(44:02)',
    genre: 'Trash alternative Metal',
  },
  {
    band: 'August Burns Red',
    title: 'Death Below',
    image: '/src/images/augustburnsred-1.jpg',
    date: 'March 24th, 2023',
    length: '(44:02)',
    genre: 'MetalCore',
  },
  {
    band: 'Dio',
    title: 'Evil or Divine',
    image: '/src/images/dio-1.jpg',
    date: 'February 22nd, 2005',
    length: '(92:39)',
    genre: 'Heavy Metal',
  },
  {
    band: 'While She Sleeps',
    title: 'This is the Six',
    image: '/src/images/whileshesleeps-1.jpg',
    date: 'August 13th, 2012',
    length: '(44:39)',
    genre: 'MetalCore',
  },
  {
    band: 'Linkin Park',
    title: 'From zero',
    image: '/src/images/linkinpark-1.jpg',
    date: 'November 15th, 2024',
    length: '(31:54)',
    genre: 'Nu Metal',
  },
  {
    band: 'Linkin Park',
    title: 'Hybrid Theory',
    image: '/src/images/linkinpark-2.jpg',
    date: 'October 24th, 2000',
    length: '(37:50)',
    genre: 'Nu Metal',
  },
  {
    band: 'Rainbow',
    title: 'The Defginitive Osaka 1978 Final night',
    image: '/src/images/rainbow-1.jpg',
    date: 'March 31st, 2023',
    length: '(111:0)',
    genre: 'Heavy Metal',
  },
  {
    band: 'Iron Maiden',
    title: 'Infinite Dreams',
    image: '/src/images/ironmaiden-5.jpg',
    date: 'November 06th, 1989',
    length: '(16:15)',
    genre: 'Heavy Metal',
  },
  {
    band: 'Nine Inch Nails',
    title: 'Pretty Hate Machine',
    image: '/src/images/nineinchnails-2.jpg',
    date: 'October 20th, 1989',
    length: '(48:47)',
    genre: 'Industrial Rock',
  },
  {
    band: 'Dio',
    title: 'Holy Diver',
    image: '/src/images/dio-2.jpg',
    date: 'May 15th, 1983',
    length: '(75:37)',
    genre: 'Heavy Metal',
  },
  {
    band: 'Iron Maiden',
    title: 'Somewhere in time',
    image: '/src/images/ironmaiden-6.jpg',
    date: 'January 01st, 1986',
    length: '(51:41)',
    genre: 'Heavy Metal',
  },
  {
    band: 'Death',
    title: 'The sound of perseverence',
    image: '/src/images/death-1.jpg',
    date: 'February 15th, 2011',
    length: '(117:15)',
    genre: 'Death Metal',
  },
  {
    band: 'Paleface Swiss',
    title: 'Cursed (The complete edition)',
    image: '/src/images/palefaceswiss-1.jpg',
    date: 'January 03rd, 2025',
    length: '(48:11)',
    genre: 'Death core',
  },
]
  

const rockcollection = [
   {
    band: 'Greta Van Fleet',
    title: "The Battle at Garden's Gate",
    image: '/src/images/gretavanfleet-1.jpg',
    date: 'June 09th, 2023',
    length: '(63:32)',
    genre: 'Rock',
  },
  {
    band: 'Greta Van Fleet',
    title: 'From the Fires',
    image: '/src/images/gretavanfleet-2.jpg',
    date: 'November 10th, 2017',
    length: '(32:11)',
    genre: 'Rock',
  },
  {
    band: 'The White Stripes',
    title: 'Elephant',
    image: '/src/images/thewhitestripes-1.jpg',
    date: 'April 01st 2003',
    length: '(50:54)',
    genre: 'Rock',
  },
  {
    band: 'The Cure',
    title: 'Desintegration',
    image: '/src/images/thecure-1.jpg',
    date: 'May 02nd, 1989',
    length: '(72:03)',
    genre: 'Gothic Rock',
  },
  {
    band: 'Pink Floyd',
    title: 'Meddle',
    image: '/src/images/pinkfloyd-1.jpg',
    date: 'November 11th, 1971',
    length: '(46:46)',
    genre: 'Rock progressive',
  },
  {
    band: 'Nine Inch Nails',
    title: 'The Downward Spiral',
    image: '/src/images/nineinchnails-1.jpg',
    date: 'July 23rd, 1984',
    length: '(65:07)',
    genre: 'Industrial Rock',
  },
  {
    band: 'Bruce Springsteen',
    title: 'Born in the USA',
    image: '/src/images/brucespringsteen-1.jpg',
    date: 'June 04th, 1984',
    length: '(46:53)',
    genre: 'Rock',
  },
  {
    band: 'Pink Floyd',
    title: 'Wish you were here',
    image: '/src/images/pinkfloyd-2.jpg',
    date: 'September 02nd, 1975',
    length: '(44:13)',
    genre: 'Rock progressive',
  },
  {
    band: 'Johnny Cash',
    title: 'American IV: The Man Comes Around',
    image: '/src/images/johnnycash-1.jpg',
    date: 'November 05th, 2002',
    length: '(51:45)',
    genre: 'County Rock',
  },
  {
    band: 'R.E.M.',
    title: 'New Adventures in Hi-Fi',
    image: '/src/images/rem-1.jpg',
    date: 'September 10th, 1996',
    length: '(65:31)',
    genre: 'Rock',
  },
  {
    band: 'Polyphia',
    title: 'Remember that you will die',
    image: '/src/images/polyphia-1.jpg',
    date: 'October 28th 2022',
    length: '(39:08)',
    genre: 'Rock progressive',
  },
  {
    band: 'Lenny Kravitz',
    title: '5',
    image: '/src/images/lennykravitz-1.jpg',
    date: 'May 12th, 1998',
    length: '(75:50)',
    genre: 'Rock',
  },
  {
    band: 'Rage Against the Machine',
    title: 'Rage Against the Machine',
    image: '/src/images/rageagainstthemachine-1.jpg',
    date: 'May 12th, 1998',
    length: '(52:53)',
    genre: 'Hardcore Punk',
  },
  {
    band: "Guns N' Roses",
    title: 'Greatest Hits',
    image: '/src/images/gunsandroses-1.jpg',
    date: 'March 23rd, 2004',
    length: '(72:14)',
    genre: 'Hard Rock',
  },
  {
    band: 'Yes',
    title: 'Going for the One',
    image: '/src/images/yes-1.jpg',
    date: 'July 07th, 1977',
    length: '(38:55)',
    genre: 'Rock, Progressive Rock',
  },
  {
    band: 'Simple Minds',
    title: 'New Gold Dream (81–82–83–84)',
    image: '/src/images/simpleminds-1.jpg',
    date: 'September 01st, 1982',
    length: '(44:59)',
    genre: 'Rock, Progressive Rock',
  },
  {
    band: 'Supertramp',
    title: 'Indelibly Stamped',
    image: '/src/images/supertramp-1.jpg',
    date: 'June 25th, 1971',
    length: '(40:06)',
    genre: 'Rock',
  },
  {
    band: 'Genesis',
    title: 'A Trick of the Tail',
    image: '/src/images/genesis-1.jpg',
    date: 'February 06th, 1976',
    length: '(51:22)',
    genre: 'Progressive Rock',
  },
  {
    band: 'The Rolling Stones',
    title: 'Their Satanic Majesties Request',
    image: '/src/images/therollingstones-1.jpg',
    date: 'December 08th, 1967',
    length: '(44:08)',
    genre: 'Rock',
  },
  {
    band: 'Supertramp',
    title: '...Famous Last Words...',
    image: '/src/images/supertramp-2.jpg',
    date: 'October 06th, 1982',
    length: '(47:58)',
    genre: 'Rock',
  },
  {
    band: 'Supertramp',
    title: 'Supertramp',
    image: '/src/images/supertramp-3.jpg',
    date: 'July 14th, 1970',
    length: '(47:50)',
    genre: 'Rock',
  },
  {
    band: 'Nazareth',
    title: 'Hair of the Dog',
    image: '/src/images/nazareth-1.jpg',
    date: 'April 03rd, 1975',
    length: '(78:21)',
    genre: 'Rock',
  },
  {
    band: 'Yes',
    title: 'Relayer',
    image: '/src/images/yes-2.jpg',
    date: 'December 05th, 1974',
    length: '(40:29)',
    genre: 'Rock, Progressive Rock',
  },
  {
    band: 'Michael Jackson',
    title: 'Ben',
    image: '/src/images/michaeljackson-1.jpg',
    date: 'August 04th, 1972',
    length: '(31:13)',
    genre: 'R and B, Soul',
  },
  {
    band: 'John Lennon',
    title: 'Imagine',
    image: '/src/images/johnlennon-1.jpg',
    date: 'September 09th, 1971',
    length: '(39:44)',
    genre: 'Rock, pop, experimental',
  },
  {
    band: 'Simple Minds',
    title: 'Sparkle in the Rain',
    image: '/src/images/simpleminds-2.jpg',
    date: 'February 06th, 1984',
    length: '(44:58)',
    genre: 'Rock, progressive Rock',
  },
  {
    band: 'Eagles',
    title: 'Hotel California',
    image: '/src/images/eagles-1.jpg',
    date: 'December 08th, 1976',
    length: '(43:25)',
    genre: 'Rock, progressive Rock',
  },
  {
    band: 'Supertramp',
    title: 'Breakfast in America',
    image: '/src/images/supertramp-4.jpg',
    date: 'March 16th, 1979',
    length: '(46:14)',
    genre: 'Rock',
  },
  {
    band: 'Janis Joplin',
    title: 'Live In Amsterdam 1969, US Radio Shows 1969-70',
    image: '/src/images/janisjoplin-1.jpg',
    date: 'November 16th, 2016',
    length: '(40:25)',
    genre: 'Rock, Blues',
  },
  {
    band: 'Pink Floyd',
    title: 'Dark Side of the Moon',
    image: '/src/images/pinkfloyd-3.jpg',
    date: 'March 01st, 1973',
    length: '(40:25)',
    genre: 'Progressive Rock',
  },
  {
    band: 'Deep Purple',
    title: 'Machine Head',
    image: '/src/images/deeppurple-1.jpg',
    date: 'March 25th, 1972',
    length: '(41:40)',
    genre: 'Rock',
  },
  {
    band: 'Depeche Mode',
    title: 'Violator',
    image: '/src/images/depechemode-1.jpg',
    date: 'March 19th, 1990',
    length: '(47:03)',
    genre: 'Electronic, New Wave',
  },
  {
    band: 'Depeche Mode',
    title: 'Black Celebration',
    image: '/src/images/depechemode-2.jpg',
    date: 'March 17th, 1987',
    length: '(55:13)',
    genre: 'Electronic, New Wave',
  },
  {
    band: 'Depeche Mode',
    title: 'Music for the Masses',
    image: '/src/images/depechemode-3.jpg',
    date: 'September 28th, 1988',
    length: '(61:58)',
    genre: 'Electronic, New Wave',
  },
  {
    band: 'Depeche Mode',
    title: 'Speak & Spell',
    image: '/src/images/depechemode-4.jpg',
    date: 'October 21st, 1981',
    length: '(61:58)',
    genre: 'Electronic, New Wave',
  },
  {
    band: 'Radiohead',
    title: 'the bends',
    image: '/src/images/radiohead-1.jpg',
    date: 'April 04th, 1995',
    length: '(48:34)',
    genre: 'Rock, Alternative Rock',
  },
  {
    band: 'Radiohead',
    title: 'Ok computer',
    image: '/src/images/radiohead-2.jpg',
    date: 'July 01st, 1997',
    length: '(53:36)',
    genre: 'Rock, Alternative Rock',
  },
  {
    band: 'Radiohead',
    title: 'Kid A MNESIA',
    image: '/src/images/radiohead-3.jpg',
    date: 'November 05th 2021',
    length: '(125:05)',
    genre: 'Rock, Alternative Rock',
  },
  {
    band: 'Téléphone',
    title: 'Best Of',
    image: '/src/images/téléphone-1.jpg',
    date: 'November 24th 2000',
    length: '(65:34)',
    genre: 'Rock',
  },
  {
    band: 'Depeche Mode',
    title: 'Memento mori Mexico city',
    image: '/src/images/depechemode-5.jpg',
    date: 'November 14th, 2025',
    length: '(140:44)',
    genre: 'Electronic, New Wave',
  },
  {
    band: 'Stereophonics',
    title: 'Graffiti on the Train',
    image: '/src/images/stereophonics-1.jpg',
    date: 'March 12th, 2013',
    length: '(43:09)',
    genre: 'Rock',
  },
  {
    band: 'Neil Diamond',
    title: 'Jonathan levingston Seagull',
    image: '/src/images/neildiamond-1.jpg',
    date: 'October 01st,1973',
    length: '(43:28)',
    genre: 'Rock, pop rock',
  },
  {
    band: 'Greta Van Fleet',
    title: 'Startcatcher',
    image: '/src/images/gretavanfleet-3.jpg',
    date: 'July 21st, 2023',
    length: '(42:49)',
    genre: 'Rock',
  },
  {
    band: 'Greta Van Fleet',
    title: 'Anthem of a peacfull army',
    image: '/src/images/gretavanfleet-4.jpg',
    date: 'October 19th, 2018',
    length: '(49:34)',
    genre: 'Rock',
  },
  {
    band: 'Supertramp',
    title: 'Crisis? What Crisis?',
    image: '/src/images/supertramp-5.jpg',
    date: 'January 01st, 1975',
    length: '(47:40)',
    genre: 'Rock',
  },
  {
    band: 'Pink Floyd',
    title: 'Relics',
    image: '/src/images/pinkfloyd-4.jpg',
    date: 'May 14th, 1971',
    length: '(49:38)',
    genre: 'Progressive Rock',
  },
  {
    band: 'Supertramp',
    title: 'Even in quietest moments...',
    image: '/src/images/supertramp-6.jpg',
    date: 'January 01st, 1977',
    length: '(43:37)',
    genre: 'Rock',
  },
  {
    band: 'Genesis',
    title: 'Trepass',
    image: '/src/images/genesis-2.jpg',
    date: 'October 01st, 1970',
    length: '(42:40)',
    genre: 'Rock',
  },
  {
    band: 'Queen',
    title: 'Innuendo',
    image: '/src/images/queen-1.jpg',
    date: 'February 01st, 1991',
    length: '(53:55)',
    genre: 'Rock',
  },
  {
    band: 'R.E.M',
    title: 'The best of R.E.M In time 1988-2003',
    image: '/src/images/rem-2.jpg',
    date: 'October 28th, 2003',
    length: '(76:07)',
    genre: 'Rock',
  },
  {
    band: 'Various Artists',
    title: 'Django unchainded Original Motion Picture Soundtrack',
    image: '/src/images/django-1.jpg',
    date: 'December 28th, 2012',
    length: '(54:28)',
    genre: 'Various',
  },
  {
    band: 'George Michael',
    title: 'Older',
    image: '/src/images/georgemichael-1.jpg',
    date: 'April 01st, 1996',
    length: '(58:88)',
    genre: 'Pop',
  },
  {
    band: 'Talking heads',
    title: 'Stop making sense',
    image: '/src/images/talkingheads-1.jpg',
    date: 'October 23rd, 1984',
    length: '(74:24)',
    genre: 'Punk rock, New wave',
  },
  {
    band: 'Nick Cave',
    title: 'The firtborn is dead',
    image: '/src/images/nickcave-1.jpg',
    date: 'June 03rd, 1985',
    length: '(40:36)',
    genre: 'Gothic, post punk',
  },
  {
    band: 'Iggy Pop & David Bowie',
    title: 'Iggy Pop & David Bowie – Live At The Rainbow Theatre March 1977 (Radio Broadcast)',
    image: '/src/images/iggypop-1.jpg',
    date: 'June 30th, 2023',
    length: '(40:36)',
    genre: 'Punk',
  },
  {
    band: 'The clash',
    title: 'London Calling Eu pressing',
    image: '/src/images/theclash-1.jpg',
    date: 'December 14th, 1979',
    length: '(65:08)',
    genre: 'Punk Rock',
  },
  {
    band: 'The Rolling Stones',
    title: "Get yer ya-ya's out!",
    image: '/src/images/therollingstones-2.jpg',
    date: 'September  04th, 1970',
    length: '(47:39)',
    genre: 'Rock',
  },
  {
    band: 'The cure',
    title: 'Songs of the lost world',
    image: '/src/images/thecure-2.jpg',
    date: 'November  01st, 2024',
    length: '(49:13)',
    genre: 'Gothic Rock',
  },
  {
    band: 'The police',
    title: "Come Back Boys, All's Forgiven",
    image: '/src/images/thepolice-1.jpg',
    date: 'June  15th, 1986',
    length: '(49:13)',
    genre: 'Rock',
  },
  {
    band: 'Status Qup',
    title: 'The Early Works',
    image: '/src/images/statusquo-1.jpg',
    date: 'December  15th, 1990',
    length: '(140:13)',
    genre: 'Rock',
  },
]

async function migrateData() {
  const allVinyls = [...metalcollection, ...rockcollection]

  console.log(`Migrating ${allVinyls.length} total records...`)

  const { data, error } = await supabase.from('vinyls').insert(allVinyls)

  if (error) {
    console.error('Error:', error)
  } else {
    console.log(`✓ Success! Migrated ${allVinyls.length} records.`)
  }
}

migrateData()