
import powerslave from './images/powerslave.jpg'
import gretavanfleet1 from './images/gretavanfleet-1.jpg'
import gretavanfleet2 from './images/gretavanfleet-2.jpg'

export const pageLinks = [
  { id: 1, href: '#home', text: 'home' },
  { id: 2, href: '#about', text: 'about the music' },
  { id: 3, href: '#top', text: 'Top 10 Albums' },
  { id: 4, href: '#collection', text: 'The collection' },
]
export const socialLinks = [
  { id: 1, href: 'https://www.facebook.com', icon: 'fab fa-facebook' },
  { id: 2, href: 'https://x.com/', icon: 'fa-brands fa-twitter' },
  { id: 3, href: 'https://www.squarespace.com', icon: 'fab fa-squarespace' },
]

export const top = [
  {
    id: 1,
    icon: 'fas fa-wallet fa-fw',
    title: 'Album#1',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 2,
    icon: 'fas fa-tree fa-fw',
    title: 'Album#2',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 3,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#3',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 4,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#4',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 5,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#5',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 6,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#6',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 7,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#6',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 8,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#8',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 9,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#9',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 10,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#10',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
]

export const toprocks = [
  {
    id: 1,
    icon: 'fas fa-wallet fa-fw',
    title: 'Album#1',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 2,
    icon: 'fas fa-tree fa-fw',
    title: 'Album#2',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 3,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#3',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 4,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#4',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 5,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#5',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 6,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#6',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 7,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#6',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 8,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#8',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 9,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#9',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
  {
    id: 10,
    icon: 'fas fa-socks fa-fw',
    title: 'Album#10',
    text: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.',
    image: powerslave,
  },
]

export const collection = [
  {
    id: 1,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
  {
    id: 2,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'ACDC',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
  {
    id: 3,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
  {
    id: 4,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
  {
    id: 5,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
]

export const collectionrock = [
  {
    id: 1,
    image: gretavanfleet1,
    title: "The Battle at Garden's Gate special edition",
    date: 'June 9th, 2023',
    info: "The Battle at Garden's Gate is the second studio album by American rock band Greta Van Fleet",
    band: 'Greta Van Fleet',
    Lenght: '63:32',
    genre: 'Rock',
  },
  {
    id: 2,
    image: gretavanfleet2,
    title: 'From the Fires',
    date: 'November 10, 2017',
    info: 'From the Fires is the second EP by American rock band Greta Van Fleet.It was released on November 10, 2017 through Lava and Republic Records. From the Fires won the Grammy Award for Best Rock Album at the 61st Grammy Awards.',
    band: 'Greta Van Fleet',
    Lenght: '32:11',
    genre: 'Rock',
  },
  {
    id: 3,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
  {
    id: 4,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
  {
    id: 5,
    image: powerslave,
    title: 'powerslave',
    date: 'July 23rd, 1984',
    info: 'Powerslave is the fifth studio album by the English heavy metal band Iron Maiden, released on 3 September 1984 through EMI Records in Europe, and on 14 September 1984, through its sister label Capitol Records, in the US.',
    band: 'Iron Maiden',
    Lenght: '51:12',
    genre: 'Heavy Metal',
  },
]
