const { MongoClient } = require('mongodb')

// Replace with your actual MongoDB connection string
const uri =
  'mongodb+srv://metalrocks7179_db_user:1TUAGasdzFtLzcN8@mydbvinyls.rodef0a.mongodb.net/?appName=MyDBVinyls&retryWrites=true&w=majority'

const client = new MongoClient(uri)

// Manually define the data without image imports
const collection = [
  {
    id: 1,
    image: '/images/ironmaiden-1.jpg',
    title: 'Powerslave',
    date: 'July 23rd, 1984',
    band: 'Iron Maiden',
    length: '(51:12)',
    genre: 'Heavy Metal',
  },
  {
    id: 2,
    image: '/images/orbitculture-1.jpg',
    title: 'Death above life',
    date: 'October 3rd, 2025',
    band: 'Orbit Culture',
    length: '(48:34)',
    genre: 'Death Metal',
  },
  {
    id: 3,
    image: '/images/orbitculture-2.jpg',
    title: 'Descent',
    date: 'August 18th, 2023',
    band: 'Orbit Culture',
    length: '(51:12)',
    genre: 'Death Metal',
  },
  {
    id: 4,
    image: '/images/whitechapel-1.jpg',
    title: 'Hymmns in Dissonance',
    date: 'March 07th, 2025',
    band: 'Whitechapel',
    length: '(43:17)',
    genre: 'Hardcore,Grindcore',
  },
  {
    id: 5,
    image: '/images/blacksabbath-1.jpg',
    title: 'Heaven and Hell',
    date: 'April 25th, 1980',
    band: 'Black Sabbath',
    length: '(39:48)',
    genre: 'Heavy Metal, Doom Metal',
  },
  {
    id: 6,
    image: '/images/neckbreakker-1.jpg',
    title: 'Within The viscera',
    date: 'December 06th, 2024',
    band: 'Neckbreakker',
    length: '(46:09)',
    genre: 'Death Metal',
  },
  {
    id: 7,
    image: '/images/lornashore-1.jpg',
    title: 'I feel the everblack festering within me',
    date: 'September 29th, 2025',
    band: 'Lorna Shore',
    length: '(66:31)',
    genre: 'Deathcore',
  },
  {
    id: 8,
    image: '/images/motorhead-1.jpg',
    title: 'Overnight session',
    date: 'October 15th 1996',
    band: 'Mötorhead',
    length: '(41:19)',
    genre: 'Heavy Rock',
  },
  {
    id: 9,
    image: '/images/sacredreich-1.jpg',
    title: 'awakening',
    date: 'August 23rd, 2019',
    band: 'Sacred Reich',
    length: '(31:28)',
    genre: 'Trash Metal',
  },
  {
    id: 10,
    image: '/images/ironmaiden-2.jpg',
    title: 'Made in England',
    date: 'March 25th, 2013',
    band: 'Iron Maiden',
    length: '(100:22)',
    genre: 'Heavy Metal',
  },
  {
    id: 11,
    image: '/images/neaera-1.jpg',
    title: 'All is dust',
    date: 'June 28th, 2024',
    band: 'Neaera',
    length: '(47:40)',
    genre: 'Death Metal',
  },
  {
    id: 12,
    image: '/images/motorhead-2.jpg',
    title: 'The Löst Tapes, Vol. 2 (Live in Norwich, 1998)',
    date: 'December 24th, 2021',
    band: 'Mötorhead',
    length: '(47:40)',
    genre: 'Death Metal',
  },
  {
    id: 13,
    image: '/images/typeofnegative-1.jpg',
    title: 'Life is killing me',
    date: 'April 19th, 2024',
    band: 'Type of Negative',
    length: '(74:33)',
    genre: 'Goth Metal',
  },
  {
    id: 14,
    image: '/images/tool-1.jpg',
    title: 'Undertow',
    date: 'January 1st, 1993',
    band: 'Tool',
    length: '(68:13)',
    genre: 'Underground Metal',
  },
  {
    id: 15,
    image: '/images/ironmaiden-3.jpg',
    title: 'The Number of the Beast',
    date: 'March 22nd, 1982',
    band: 'Iron Maiden',
    length: '(40:22)',
    genre: 'Heavy Metal',
  },
  {
    id: 16,
    image: '/images/theblackdahlia-1.jpg',
    title: 'Servitude',
    date: 'September 27th, 2024',
    band: 'The Black Dahlia Murder',
    length: '(32:49)',
    genre: 'Death Metal',
  },
  {
    id: 17,
    image: '/images/killswitch-1.jpg',
    title: 'Atonement',
    date: 'August 16th, 2019',
    band: 'Killswitch Engage',
    length: '(39:02)',
    genre: 'Death Metal',
  },
  {
    id: 18,
    image: '/images/opeth-1.jpg',
    title: 'Ghost reveries',
    date: 'August 30th, 2005',
    band: 'Opeth',
    length: '(66:46)',
    genre: 'Doom Death Metal, Progressive Metal',
  },
  {
    id: 19,
    image: '/images/borknagar-1.jpg',
    title: 'Fall',
    date: 'February 23rd, 2024',
    band: 'Borknagar',
    length: '(54:30)',
    genre: 'Progressive Metal',
  },
  {
    id: 20,
    image: '/images/ironmaiden-4.jpg',
    title: 'Life after death',
    date: 'August 1st, 1985',
    band: 'Iron Maiden',
    length: '(102:54)',
    genre: 'Heavy Metal',
  },
  {
    id: 21,
    image: '/images/systemofadown-1.jpg',
    title: 'Toxicity',
    date: 'September 4th, 2001',
    band: 'System of a Down',
    length: '(44:02)',
    genre: 'Trash alternative Metal',
  },
  {
    id: 22,
    image: '/images/augustburnsred-1.jpg',
    title: 'Death Below',
    date: 'March 24th, 2023',
    band: 'August Burns Red',
    length: '(44:02)',
    genre: 'MetalCore',
  },
  {
    id: 24,
    image: '/images/dio-1.jpg',
    title: 'Evil or Divine',
    date: 'February 22nd, 2005',
    band: 'Dio',
    length: '(92:39)',
    genre: 'Heavy Metal',
  },
  {
    id: 25,
    image: '/images/whileshesleeps-1.jpg',
    title: 'This is the Six',
    date: 'August 13th, 2012',
    band: 'While She Sleeps',
    length: '(44:39)',
    genre: 'MetalCore',
  },
  {
    id: 26,
    image: '/images/linkinpark-1.jpg',
    title: 'From zero',
    date: 'November 15th, 2024',
    band: 'Linkin Park',
    length: '(31:54)',
    genre: 'Nu Metal',
  },
  {
    id: 27,
    image: '/images/linkinpark-2.jpg',
    title: 'Hybrid Theory',
    date: 'October 24th, 2000',
    band: 'Linkin Park',
    length: '(37:50)',
    genre: 'Nu Metal',
  },
  {
    id: 28,
    image: '/images/rainbow-1.jpg',
    title: 'The Defginitive Osaka 1978 Final night',
    date: 'March 31st, 2023',
    band: 'Rainbow',
    length: '(111:0)',
    genre: 'Heavy Metal',
  },
  {
    id: 29,
    image: '/images/ironmaiden-5.jpg',
    title: 'Infinite Dreams',
    date: 'November 6th, 1989',
    band: 'Iron Maiden',
    length: '(16:15)',
    genre: 'Heavy Metal',
  },
  {
    id: 30,
    image: '/images/nineinchnails-2.jpg',
    title: 'Pretty Hate Machine',
    date: 'October 20th, 1989',
    band: 'Nine Inch Nails',
    length: '(48:47)',
    genre: 'Industrial Rock',
  },
  {
    id: 31,
    image: '/images/dio-2.jpg',
    title: 'Holy Diver',
    date: 'May 15th, 1983',
    band: 'Dio',
    length: '(75:37)',
    genre: 'Heavy Metal',
  },
  {
    id: 32,
    image: '/images/ironmaiden-6.jpg',
    title: 'Somewhere in time',
    date: 'January 1st, 1986',
    band: 'Iron Maiden',
    length: '(51:41)',
    genre: 'Heavy Metal',
  },
]

const collectionrock = [
  {
    id: 1,
    image: '/images/gretavanfleet-1.jpg',
    title: "The Battle at Garden's Gate",
    date: 'June 9th, 2023',
    band: 'Greta Van Fleet',
    length: '(63:32)',
    genre: 'Rock',
  },
  {
    id: 2,
    image: '/images/gretavanfleet-2.jpg',
    title: 'From the Fires',
    date: 'November 10th, 2017',
    band: 'Greta Van Fleet',
    length: '(32:11)',
    genre: 'Rock',
  },
  {
    id: 3,
    image: '/images/thewhitestripes-1.jpg',
    title: 'Elephant',
    date: 'April 1st 2003',
    band: 'The White Stripes',
    length: '(50:54)',
    genre: 'Rock',
  },
  {
    id: 4,
    image: '/images/thecure-1.jpg',
    title: 'Desintegration',
    date: 'May 02nd, 1989',
    band: 'The Cure',
    length: '(72:03)',
    genre: 'Rock',
  },
  {
    id: 5,
    image: '/images/pinkfloyd-1.jpg',
    title: 'Meddle',
    date: 'November 11th, 1971',
    band: 'Pink Floyd',
    length: '(46:46)',
    genre: 'Rock progressive',
  },
  {
    id: 6,
    image: '/images/nineinchnails-1.jpg',
    title: 'The Downward Spiral',
    date: 'July 23rd, 1984',
    band: 'Nine Inch Nails',
    length: '(65:07)',
    genre: 'Industrial Rock',
  },
  {
    id: 7,
    image: '/images/brucespringsteen-1.jpg',
    title: 'Born in the USA',
    date: 'June 04, 1984',
    band: 'Bruce Springsteen',
    length: '(46:53)',
    genre: 'Rock',
  },
  {
    id: 8,
    image: '/images/pinkfloyd-2.jpg',
    title: 'Wish you were here',
    date: 'September 02nd, 1975',
    band: 'Pink Floyd',
    length: '(44:13)',
    genre: 'Rock progressive',
  },
  {
    id: 9,
    image: '/images/johnnycash-1.jpg',
    title: 'American IV: The Man Comes Around',
    date: 'November 5th, 2002',
    band: 'Johnny Cash',
    length: '(51:45)',
    genre: 'County Rock',
  },
  {
    id: 10,
    image: '/images/rem-1.jpg',
    title: 'New Adventures in Hi-Fi',
    date: 'September 10th, 1996',
    band: 'R.E.M.',
    length: '(65:31)',
    genre: 'Rock',
  },
  {
    id: 11,
    image: '/images/polyphia-1.jpg',
    title: 'Remember that you will die',
    date: 'October 28th 2022',
    band: 'Polyphia',
    length: '(39:08)',
    genre: 'Rock progressive',
  },
  {
    id: 12,
    image: '/images/lennykravitz-1.jpg',
    title: '5',
    date: 'May 12th, 1998',
    band: 'Lenny Kravitz',
    length: '(75:50)',
    genre: 'Rock',
  },
  {
    id: 13,
    image: '/images/rageagainstthemachine-1.jpg',
    title: 'Rage Against the Machine',
    date: 'May 12th, 1998',
    band: 'Rage Against the Machine',
    length: '(52:53)',
    genre: 'Hardcore Punk',
  },
  {
    id: 14,
    image: '/images/gunsandroses-1.jpg',
    title: 'Greatest Hits',
    date: 'March 23rd, 2004',
    band: "Guns N' Roses",
    length: '(72:14)',
    genre: 'Hard Rock',
  },
  {
    id: 15,
    image: '/images/yes-1.jpg',
    title: 'Going for the One',
    date: 'July 07th, 1977',
    band: 'Yes',
    length: '(38:55)',
    genre: 'Rock, Progressive Rock',
  },
  {
    id: 16,
    image: '/images/simpleminds-1.jpg',
    title: 'New Gold Dream (81–82–83–84)',
    date: 'September 1st, 1982',
    band: 'Simple Minds',
    length: '(44:59)',
    genre: 'Rock, Progressive Rock',
  },
  {
    id: 17,
    image: '/images/supertramp-1.jpg',
    title: 'Indelibly Stamped',
    date: 'June 25th, 1971',
    band: 'Supertramp',
    length: '(40:06)',
    genre: 'Rock',
  },
  {
    id: 18,
    image: '/images/genesis-1.jpg',
    title: 'A Trick of the Tail',
    date: 'February 06th, 1976',
    band: 'Genesis',
    length: '(51:22)',
    genre: 'Progressive Rock',
  },
  {
    id: 19,
    image: '/images/therollingstones-1.jpg',
    title: 'Their Satanic Majesties Request',
    date: 'December 8th, 1967',
    band: 'The Rolling Stones',
    length: '(44:08)',
    genre: 'Rock',
  },
  {
    id: 20,
    image: '/images/supertramp-2.jpg',
    title: '...Famous Last Words...',
    date: 'October 6th, 1982',
    band: 'Supertramp',
    length: '(47:58)',
    genre: 'Rock',
  },
  {
    id: 21,
    image: '/images/supertramp-3.jpg',
    title: 'Supertramp',
    date: 'July 14th, 1970',
    band: 'Supertramp',
    length: '(47:50)',
    genre: 'Rock',
  },
  {
    id: 22,
    image: '/images/nazareth-1.jpg',
    title: 'Hair of the Dog',
    date: 'April 3rd, 1975',
    band: 'Nazareth',
    length: '(78:21)',
    genre: 'Rock',
  },
]

async function uploadData() {
  try {
    await client.connect()
    console.log('Connected to MongoDB!')

    const database = client.db('vinyls_database')

    // Upload metal collection
    const metalCollection = database.collection('metal_albums')
    await metalCollection.deleteMany({})
    const metalResult = await metalCollection.insertMany(collection)
    console.log(`✅ ${metalResult.insertedCount} metal albums inserted`)

    // Upload rock collection
    const rockCollection = database.collection('rock_albums')
    await rockCollection.deleteMany({})
    const rockResult = await rockCollection.insertMany(collectionrock)
    console.log(`✅ ${rockResult.insertedCount} rock albums inserted`)

    console.log('\n🎸 All vinyl data uploaded successfully!')
  } catch (error) {
    console.error('❌ Error uploading data:', error)
  } finally {
    await client.close()
  }
}

uploadData()
